[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-session = { version = "0.8", features = ["cookie-session"]}
actix-web-httpauth = "0.7"  # For BearerAuth
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.10"
mime = "0.3"
lazy_static = "1.4"  # For mock user database
bcrypt = "0.13"
lettre = { version = "0.11", features = ["smtp-transport", "tokio1-native-tls"] }
lettre_email = "0.9.4"
tokio = { version = "1.0", features = ["full"] }
reqwest = "0.12.15"
actix-cors = "0.6.0"
uuid = { version = "1.0", features = ["v4"] }
chrono = "0.4.41"
jsonwebtoken = "9.2"
dotenv = "0.15.0"
# zstd = { version = "0.12", features = [] }
# zstd-safe = { version = "7.0", default-features = false }
# zstd-sys = { version = "2.0", default-features = false, features = ["pkg-config"] }
log = "0.4"
